### ISSUE TITLE
[Advice] How to pass unique IDs with coordinates?

### ISSUE THREAD

**Issue by do-me** [oliviaguest/weighted_k_means#4]
First of all: great repo! 
Not an issue but rather some advice needed. When passing my data I would like to pass an id for every coordinate in order to process the data afterwards. 

Assume this data where `lat`, `lon `are the coordinates (`X`) and weight is the variable `c`. My aim is to fill the column `cluster` which I would normally do via a simple pandas merge command, pretty much like in [this medium article for sklearn's kmeans (see step 6)](https://medium.com/@dey.mallika/unsupervised-learning-with-weighted-k-means-3828b708d75d).

| id | lat      | lon     | weight | cluster |
|----|----------|---------|--------|---------|
| 1  | 50.34623 | 8.23523 | 2000   | ?       |
| 2  | 50.2345  | 9.23552 | 1000   | ?       |
| 3  | 50.643   | 9.23523 | 1000   | ?       |
|...|...|...|...|...|

As your wkmeans method doesn't have the function `predicted_kmeans = kmeans.predict(X, sample_weight = Y)` I was wondering what the easiest way was to fill the cluster column. 

My main idea was to create a fake id by concatting lat+lon but this would lead to issues with duplicates. 

I tried creating a 3D-array with lat, lon and id but it returned - for my use-case - "false" 3D-results. 

Currently, I'm just passing the data from a pandas df.

```
X = np.array(df[["lon","lat"]].astype(float))
c = np.array(df['weight'].astype(float)) 
```
Any advice? 

Thanks in advance!

**Comment by oliviaguest** [comment]
I'm confused. Do you want a cluster ID per coordinate or a coordinate ID?

**Comment by do-me** [comment]
I'd like a cluster ID per coordinate (and respective weight!) in order to fill the above table where you can see the question mark. Is there any useful method I could use?

**Comment by oliviaguest** [comment]
I don't understand why you cannot use the value of, e.g., m, as defined on line: https://github.com/oliviaguest/weighted_k_means/blob/master/wkmeans.py#L175? I might be missing something important of course!

**Comment by do-me** [comment]
I wasn't precise enough. Unfortunately m or simply 'wkmeans.clusters' doesn't help as there is **no more link to the original table/data**. 
Let's take this example table to start with and suppose we want to find 5 clusters: 1,2,3,4,5.

| id |name|age| lat      | lon     | weight | cluster |
|----|---------|-----|----------|---------|--------|---------|
| 1  | alex|30|50.34623 | 8.23523 | 2000   | ?       |
| 2  | nora|25|50.2345  | 9.23552 | 1000   | ?       |
| 3  | laura| 34|50.643   | 9.23523 | 1000   | ?       |
| 4  | peter| 39|50.643   | 9.23523 | 2000   | ?       |
|...|...|...|...|...|...|...|

How would you use wkmeans to fill **this original table** with the respective cluster numbers 1,2,3,4,5 (column cluster)? 

---

This is what I did until now:

```
X = np.array(df[["lon","lat"]].astype(float))# x y cols
Y = np.array(df["weight"].astype(float)) # z col
```

As the variables X and Y take only numeric values, I cannot pass the full data including id, name, age etc. 

```
wkmeans = wkm.KPlusPlus(5, X=X, c=Y, alpha=3, beta=0.9)#, max_runs=3) 
wkmeans.init_centers()
wkmeans.find_centers(method='++')
```

With `wkmeans.clusters` I get only the coordinates as cluster array. As you proposed, the array index is my cluster number. 

```
[[array([ 8.12345, 50.12345]),
  array([ 8.54321 , 50.54321]), ... , ]]

```
So with only the coordinates in an array I cannot unambiguously fill the above table as the last two entries are also coordinate duplicates.

I hope this makes it clearer!

**Comment by oliviaguest** [comment]
You would need to edit the code — you are right.

**Comment by do-me** [comment]
Thanks for the reply. For anyone in the same situation consider this (ugly but working) code:

1. Create a "fake-id" from lat lon in the beginning.

`df["fake-id"] = df["lon_cum"].apply(str) + "|" + df["lat_cum"].apply(str)`

If there are duplicates (like in my example) don't work with original lat lon but with `cumcount()`-altered lat lon in order to generate unique fake-ids.

```
def leading_zeros(val):
    # 999 999 999 duplicates possible
    return ("0"* (9 - len(str(val))) + str(val))
# leading_zeros(100) -> '000000100'
# leading_zeros(1)   -> '000000001'

df['lat_dup'] = df.groupby(['lat']).cumcount()+1
df['lon_dup'] = df.groupby(['lon']).cumcount()+1

# add tiny float, makes no difference in reality
df["lat_cum"] = df["lat"].map(str) + df['lat_dup'].map(leading_zeros)
df["lon_cum"] = df["lon"].map(str) + df['lat_dup'].map(leading_zeros)

del df['lat_dup'] 
del df['lon_dup'] 
```

Perform wkmeans.

2. Create a dict from wkmeans result

```
cf = pd.DataFrame(wkmeans.clusters)
cf = cf.T

def arr_to_str(i):
    try:
        return str(i[0])+"|"+str(i[1])
    except:
        return ""

cf = cf.applymap(arr_to_str)
hdic = cf.to_dict('records')

h1 = []
for i in hdic:
    h1.append({y:x for x,y in i.items()})

h2 = {}
for e in h1:
    h2.update(e)
```

3. Iterate over df (mapping would be faster) and add cluster num

```
df["cluster"] = ""
for index, row in df.iterrows():
    try:
        row["cluster"] = h2[row["fid"]]
        df.loc[index, 'cluster'] = h2[row["fid"]]
    except:
        pass
```

This method works pretty well for me.
